"""add_cascade_deletes

Revision ID: 87e101d05ee9
Revises: 78939417125a
Create Date: 2026-05-29 13:52:44.243849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e101d05ee9'
down_revision: Union[str, Sequence[str], None] = '78939417125a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('insights_company_id_fkey'), 'insights', type_='foreignkey')
    op.create_foreign_key(None, 'insights', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('inventory_product_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('orders_product_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('predictions_company_id_fkey'), 'predictions', type_='foreignkey')
    op.create_foreign_key(None, 'predictions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('products_company_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('shipments_supplier_id_fkey'), 'shipments', type_='foreignkey')
    op.create_foreign_key(None, 'shipments', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('suppliers_company_id_fkey'), 'suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_company_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_company_id_fkey'), 'users', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.create_foreign_key(op.f('suppliers_company_id_fkey'), 'suppliers', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.create_foreign_key(op.f('shipments_supplier_id_fkey'), 'shipments', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_company_id_fkey'), 'products', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_foreign_key(op.f('predictions_company_id_fkey'), 'predictions', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_product_id_fkey'), 'orders', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_product_id_fkey'), 'inventory', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'insights', type_='foreignkey')
    op.create_foreign_key(op.f('insights_company_id_fkey'), 'insights', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
